### ISSUE TITLE
Java OutOfMemoryError in latest revision

### ISSUE THREAD

**Issue by MichaelAquilina** [MichaelAquilina/SpamFilter#17]
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
    at train.EmailClassifier.extractVectors(EmailClassifier.java:146)
    at train.EmailClassifier.train(EmailClassifier.java:81)
    at train.CrossValidation.fold(CrossValidation.java:51)
    at train.Train.testClassifier(Train.java:19)
    at train.Train.main(Train.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)

**Comment by xhochy** [comment]
Just run with -Xmx4g or -Xmx6G as the default is currently using no trimming/parsing on the mails/words.

**Comment by MichaelAquilina** [comment]
Was introduced quite recently though right? 

Its using the Naive Bayes classifier right now so whats changed out of curiosity?

**Comment by xhochy** [comment]
This is simply split words by space and use Naive Bayes without any preprocessing. This is the 0.95 accuracy version which should not be that good

**Comment by MichaelAquilina** [comment]
![memory-arghhh](https://f.cloud.github.com/assets/2650040/1698189/dbcfcd30-5f35-11e3-8909-12c614546509.png)

It doesnt seem to be stopping anytime soon :P

**Comment by xhochy** [comment]
I ran it yesterday with -Xmx6g on the train and it went well :P

**Comment by MichaelAquilina** [comment]
Oh I see whats causing it now  f0ce091776b

I dont think hiding something like this is going to benefit us though? Shouldnt we investigate the issue and see why Naive Bayes is performing so well? Its the kind of stuff we should write about in our report

**Comment by MichaelAquilina** [comment]
Enabling feature selection again gives me an accuracy of 85% on Naive Bayes, so not sure what changed there.

**Comment by xhochy** [comment]
Yeah, I have turned it off to debug the "plain" run and analyze if there is some "bug" causing it to be so good

**Comment by xhochy** [comment]
Maybe we are just trimming the important words?

**Comment by MichaelAquilina** [comment]
In what sense? 

Right now feature selection removes all words with a document frequency less than 7% and more than 90%

The idea is that words rarely found share among documents are not going to contribute to being able to identify between Ham and Spam.

On the other end, very frequent words are also not going to do much (they act a bit like stopwords in the given scenario).

You can twiddle with the parameters to see if this gives you better results (see the train method), but I don't think we should disable feature selection just because Naive Bayes is giving us good performance! :P

I mean he doesn't say that we _have_ to get a better classifier, just that we have to compare it. If it happens that our solution is such that Naive Bayes really gives good performance - I think its a good thing not a bad :)

**Comment by xhochy** [comment]
Oh, I thought we need to be better than Naive Bayes, just read that is "random". Ouch. too much panic from me, sorry.

Actually rare words can distinguish, e.g. there might be 5 mails using the word viagra, all spam, none in a ham mail. But 5 may be a rare number altough viagra is a good indicator for spam.

With the knowledge that we only have to be better than random, parameter tweaking sounds like the right thing to do. Naive Bayes without preprocessing might lead to good results but at the cost of a bad runtime. Slightly worse scores with a lot better runtime will be something good ;)

**Comment by MichaelAquilina** [comment]
Well If we want to include all rare words we can set the 90% to 100% as the upper bound :) I think something like 95-99% would be better though to prevent very high dimensions :)

**Comment by xhochy** [comment]
Depends a bit on the classifier, Naive Bayes will be able to cope with it in this setting, but KNN will likely just produce random results. In the end we should try these settings and report (and analyze) them.

**Comment by MichaelAquilina** [comment]
Very much agreed! 

It would be ideal if we could be able to quickly tweak these settings for each classifier, since each one could very much depend on the type of feature selection we use, the type of feature weighting, amount of preprocessing etc...

The ideal case would be to load these settings from a JSON / conf file so that we can commit separate settings for each classifier to the repository. But obviously this is extra work I'm not sure well have the time for.
