### ISSUE TITLE
Improve Memory Usage by passing a generator to the classifier rather than a list

### ISSUE THREAD

**Issue by MichaelAquilina** [MichaelAquilina/SpamFilter#18]
Using a generator means that:
- The classifier asks for a vector
- We generate the vector
- Classifier uses the vector
- vector is discarded
- repeat until no more vectors can be generated

This prevents e.g. 5000 vectors from residing in memory at one go and should solve a lot of memory and performance issues for us.

**Comment by MichaelAquilina** [comment]
I have a working implementation of this, but for some reason memory is not being cleaned between each iteration. I have a feeling it must be some form of internal optimisation used by the JVM that is pre-fetching alot of items.

**Comment by xhochy** [comment]
The JVM normally only cleans memory when it needs more. Most of the time it will just reorder objects in memory in a way no one unterstands. As long as you do not get OOM errors, it should be ok. To test if you are using less memory, run a lower -Xmx and see if it OOMs

**Comment by MichaelAquilina** [comment]
Removing -Xmx actually seems to have actually made this work. Interesting, learned something new about the JVM today hehe

What should I do, do we include this change or is it not worth the slight addition of complexity?
