### ISSUE TITLE
Write Report

### ISSUE THREAD

**Issue by MichaelAquilina** [MichaelAquilina/SpamFilter#19]
How are we going to organise the report?

I think I should write about the following since I wrote most of them:
- Feature Selection
  - zipfian distribution
  - trimming very common words and very rare words
- Feature Weighting
- Text Pre-Processing
- Inverted Index Structure (Although this can probably be left out since it does not have much to do with the actual report)

I can also write about the KNN algorithm once I write it.

Other sections we deffinately need to include:
- Naive Bayes implementation
- Info on Decision Tree
- Info on Perceptron
- Results (+ what was used e.g. cross validation) including accuracy, recall etc...

Any input on this @xhochy ?

**Comment by xhochy** [comment]
- Weka has a KNN, but as a clusterer, not classifier. Slightly different interface but should be able to act as a classifier after an initial clustering
- I should write about the E-Mail Parsing
- We should make some figures/tables, basically we need the numbers first, so we should really start making some runs to get them. 
- More parameter values for the Decision Tree and if possible we should state why we have choosen them (sadly we're in ML were stuff magically works)

**Comment by xhochy** [comment]
I'm going to split this up into subissues, so we can assign each to the one who is working on them

**Comment by MichaelAquilina** [comment]
Sounds like a plan!

On Wed, Dec 11, 2013 at 12:33 PM, Uwe L. Korn notifications@github.comwrote:

> I'm going to split this up into subissues, so we can assign each to the
> one who is working on them
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/KillaW0lf04/SpamFilter/issues/19#issuecomment-30316587
> .

## 

Michael Aquilina
