### ISSUE TITLE
Write about Text Processing

### ISSUE THREAD

**Issue by xhochy** [MichaelAquilina/SpamFilter#27]
- Stemming
- domain extraction
- symbol and attribute removal
- conflation of common terms
- lowercase
- (Future Improvement) Spell correction

**Comment by MichaelAquilina** [comment]
Stemming was completed in 5ef41ae

**Comment by MichaelAquilina** [comment]
Going to start working on "Simple Text Processing"

**Comment by MichaelAquilina** [comment]
Finished 
- Domain Extraction
- Symbol and Attribute Rmoveal
- Lowercase
- Stemming

Will leave spell correction for the end
