### ISSUE TITLE
Implement tfidf feature weighting

### ISSUE THREAD

**Issue by MichaelAquilina** [MichaelAquilina/SpamFilter#3]
Implement feature weighting with tfidf in VectorFactory.java

**Comment by MichaelAquilina** [comment]
Make sure this is made optional. We need a way of comparing the performance of classification using:
- Frequency Weighting
- tfidf weighting
- anything else we choose to use

**Comment by MichaelAquilina** [comment]
Possibly implement an IFeatureWeighting interface to swap between different schemes. Your thoughts @xhochy ?

**Comment by xhochy** [comment]
Interface which we could pass would be a good idea but you need to get rid of your C# habit of prefixing interfaces with I :-P

**Comment by MichaelAquilina** [comment]
Oh right, sorry - old habits die hard!

**Comment by MichaelAquilina** [comment]
Tfidf weighting is available as a FeatureWeighting implementation under the class TfidfWeighting.

Its currently not AS good as frequency weighting but we still have to test it on other models and the actual test set.
