### ISSUE TITLE
Re-add Stopword Removal

### ISSUE THREAD

**Issue by MichaelAquilina** [MichaelAquilina/SpamFilter#40]
From analysing the data I am noticing there are a lot of known stopwords included with the selected features. If time permits, we should re-introduce stopword removal during the text processing phase.

**Comment by xhochy** [comment]
NO NO NO

This will mess up all my Naive Bayes feature selection

**Comment by MichaelAquilina** [comment]
Lol dw I understand! I just put this issue up just to make myself aware that the issue exists. Wasnt going to implement it with the time constraints dw :)
